var ArticleConstants = {
  ARTICLE_RECEIVED: "ARTICLE_RECEIVED",
  ARTICLES_RECEIVED: "ARTICLES_RECEIVED",
  ARTICLE_REMOVED: "ARTICLE_REMOVED",
  USER_RECEIVED: "USER_RECEIVED",
  COMMENT_RECEIVED: "COMMENT_RECEIVED",
  ANNOTATION_RECEIVED: "ANNOTATION_RECEIVED"
};

module.exports = ArticleConstants;
