var ArticleConstants = {
  ARTICLE_RECEIVED: "ARTICLE_RECEIVED",
  ARTICLES_RECEIVED: "ARTICLES_RECEIVED",
  ARTICLE_REMOVED: "ARTICLE_REMOVED",
  USER_RECEIVED: "USER_RECEIVED",
  COMMENT_RECEIVED: "COMMENT_RECEIVED",
  COMMENTS_RECEIVED: "COMMENTS_RECEIVED",
  COMMENT_REMOVED: "COMMENT_REMOVED",
  ANNOTATION_RECEIVED: "ANNOTATION_RECEIVED",
  ANNOTATIONS_RECEIVED: "ANNOTATIONS_RECEIVED",
  ANNOTATION_REMOVED: "ANNOTATION_REMOVED"
};

module.exports = ArticleConstants;
